### ISSUE TITLE
Warning with $join property

### ISSUE THREAD

**Issue by SpinyMan** [stephenharris/WP-Query-Builder#1]
This line of code (Query.php:372) produces warning if `$this->joins` is not an array:
`if(count($this->joins) === 0){`

**Comment by stephenharris** [comment]
Thanks @SpinyMan - I was running on PHP 7.1 and wasn't getting any notices. Seems it was a [PHP7.2 change](http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types).

**Comment by SpinyMan** [comment]
Please update package on packagist.org!

**Comment by stephenharris** [comment]
@SpinyMan You misunderstood me. I have fixed it (but not yet published on packagist - I'll do that over the weekend). I simply meant that there is no warning on PHP 7.1 - it was introduced in PHP7.2.

**Comment by SpinyMan** [comment]
@stephenharris thanx, bro)
