### ISSUE TITLE
Still Maintained ?

### ISSUE THREAD

**Issue by varunsridharan** [stephenharris/WP-Query-Builder#2]
Is this project still Maintained ?

**Comment by stephenharris** [comment]
Yes

**Comment by varunsridharan** [comment]
@stephenharris thanks for your reply. i did not see any updates since july 2018 thats why i asked.

**Comment by varunsridharan** [comment]
@stephenharris does this integrates deeply with WPDB or it uses `wpdb->query` function to run all the query ?

**Comment by stephenharris** [comment]
Yes, there's no new 'features' I'm currently adding, but its supported in terms of bug fixes.

It uses query method of WPDB mostly, but also uses insert method for inserting rows.

Its intended as a wrapper for a wrapper for WPDB to provide a more convenient and safer interface for interacting with custom tables. Its not intended as a replacement for high-level functions like WP_Query or get_posts
